from os import system
from time import sleep

print("Welcome to easy quiz :)")
print("1 = Start")
print("2 = exit :(")
print('3 = Stuff')
picks = input("Pick = ")
if picks == "1":
    system('cls')
    print("Whats 80 + 55 ")
    print("1 = 85")
    print("2 = 135")
    guess = input("Pick = ")
    if guess == "1":
        system('cls')
        print("Wrong :(")
        print("Whats 2+2")
        print("1 = 4")
        print("2 = 22")
        guess2 = input("Pick = ")
        if guess2 == "2":
            system('cls')
            print("Ha Ha Soooooo funny")
            print("Get outta here")
            sleep(3)
            system('cls')
            print("Quick Ending")
            sleep(5)
            exit()
        if guess2 == "1":
            system("cls")
            print("Congrats You unlock Hard Mode")
            print("Do you want hard mode?")
            print("1 = Yes")
            one = input("Pick = ")
            if one == "1":
                system('cls')
                print("Whats 40 x 5")
                print("1 = 435")
                print("2 = 200")
                guess3 = input("Pick = ")
                if guess3 == "1":
                    system('cls')
                    print("You Trickster >:(")
                    sleep(3)
                    system('cls')
                    print("Trick Ending")
                    sleep(5)
                    exit()
                if guess3 == '2':
                    system('cls')
                    print("Whats 973 x 44")
                    print("1 = 42813")
                    print("2 = 42812")
                    guess4 = input("Pick = ")
                    if guess4 == "1":
                        system('cls')
                        print("Im annoyed :(")
                        print("exit()")
                        sleep(3)
                        print("Forced Exit Ending")
                        sleep(5)
                        exit()
                    if guess4 == "2":
                        system('cls')
                        loop = True
                        while loop:
                            print("whats 890 x 581")
                            print("1 = 517090")
                            print("2 = 630046")
                            guess5 = input("Pick = ")
                            if guess5 == "1":
                                system('cls')
                                loop = False
                            if guess5 == '2':
                                print('no')
                        print("Whats 45678 + 56789")
                        print("1 = 102467")
                        print("2 = 242946")
                        guess6 = input("Pick = ")
                        if guess6 == "1":
                            system('cls')
                            print("Congrats You Completed Hard mode :)")
                            sleep(3)
                            system('cls')
                            print("Hard Completer Ending")
                            sleep(5)
                            exit()
                        if guess6 == "2":
                            system('cla')
                            print('I like how you throw it out')
                            sleep(3)
                            system('cls')
                            print('Throw away Ending')
                            sleep(5)
                            exit()
    if guess == "2":
        system('cls')
        print('Whats 74 + 90')
        print('1 = 154')
        print('2 = 164')
        guess7 = input('Pick = ')
        if guess7 == '1':
            system('cls')
            print("Congrats you unlocked Baby Mode")
            print('do you want Baby Mode?')
            print('1 = Yes')
            print('2 = no')
            two = input("Pick = ")
            if two == '2':
                system("cls")
                print('Whatever i guess')
                print('Go Away')
                sleep(3)
                system('cls')
                print('Reject Ending')
                sleep(5)
                exit()
            if two == '1':
                system('cls')
                print('Whats 1 + 1')
                print('1 = 11')
                print('2 = 2')
                guess8 = input("Pick = ")
                if guess8 == '2':
                    system('cls')
                    print("Whats 9 + 1")
                    print('1 = 24')
                    print('2 = 10')
                    guess9 = input('Pick = ')
                    if guess9 == "2":
                        system('cls')
                        print("Whats 10 + 9")
                        print('1 = 19')
                        print('2 = 11')
                        guess10 = input('Pick = ')
                        if guess10 == "1":
                            system('cls')
                            print("Congrats you completed baby mode")
                            sleep(3)
                            system('cls')
                            print('Baby Ending')
                            sleep(5)
                            exit()
                system('cls')
                print("You arent supposed to be here.....")
                sleep(3)
                system('cls')
                print('Lost Ending')
                sleep(5)
                exit()
        if guess7 == '2':
            system('cls')
            print('Whats 30 + 9')
            print('1 = 40')
            print('2 = 39')
            guess11 = input('Pick = ')
            if guess11 == '1':
                system('cls')
                print('Congrats you unlock minus branch')
                print('1 = yes')
                three = input('Pick = ')
                if three == "3":
                    system('cls')
                    print("Whats -830 + 39")
                    print('1 = -869')
                    print('2 = -791')
                    guess12 = input('Pick = ')
                    if guess12 == "1":
                        system('cls')
                        print('Lol negative numbersssssssssssssssssssssssss')
                        sleep(3)
                        system('cls')
                        print('Negative Confusion Ending')
                        sleep(5)
                        exit()
                    if guess12 == "2":
                        system('cls')
                        print('Whats 24 - (-39)')
                        print('1 = 73')
                        print('2 = 63')
                        guess13 = input('Pick = ')
                        if guess13 == "1":
                            system('cls')
                            print('.....................................................')
                            sleep(3)
                            system('cls')
                            print('Ghost Ending')
                            sleep(5)
                            exit()
                        if guess13 == '2':
                            system('cls')
                            print('Negative :(')
                            sleep(3)
                            system('cls')
                            print('Negative Ending')
                            sleep(5)
                            exit()
            if guess11 == '2':
                system('cls')
                print('Whats 833 + 231')
                print('1 = 1064')
                print('2 = 742')
                print('3 = C̴̨̼̬̼̮͇̫̹͉͇̟̺͒͂͑̀̓̌̈̂̓͛̄̓̑͊ͅȍ̸̧̧͈͉̣̹̖̼̟̗̝̿́͛̀̏̿̈́͝ŗ̸̧͉͓͈̜̻͚̤̬̺̙̝͚̔͝r̸̥͋͂͌̅̎͗̒͑ũ̴̧͚̬͓̜̪̘̰̬̘͖̍̔͆͘͜͝ͅṗ̴̧̬̳̪̟̺͓͈͌̌t̵͕̹̣̱͍͙͜͜͝')
                guessfin = input('pick')
                if guessfin == '3':
                    system('cls')
                    print('W̷̧̻͕͙̣͍̋͆̄̎̋̔̆̄̚h̸͓̫̱͚̝̓a̸̛̤͓̰͍̦̳̖̗̦͍̅͊̽͑̐̂͋̈́̈́̀̈t̸̨̛̥̜̪͚̭̺̥͉̣̞͗̌̐̌̀̕͜͜ ̴̞̹̹͖͎̦͂̃͑̔̎H̵̨̛͇͔̱̞̲̩͉̺̺̲̰̠͍͒̿̈́̔̽̇̍̈́̾͋̕͜͠ě̵̢̡̡̥̻̘̝̺̓̿̈́̍̃̏̂̐̍̓̈́͒̋̿l̸̛͍͖̭̥̻̜̭̖͍̩͗͊̾̄̏̑ͅp̷̢̝̅͑')
                    sleep(3)
                    system('cls')
                    print('Corrupt Ending')
                    sleep(5)
                    exit()
                if guessfin == '2':
                    system('cls')
                    print('lol wrong')
                    sleep(3)
                    system('cls')
                    print("lol ending")
                    sleep(5)
                    exit()
                if guessfin == '1':
                    system('cls')
                    print('Yayyyyy')
                    sleep(3)
                    system('cls')
                    print('end')
                    sleep(5)
                    exit()
if picks == '2':
    exit()
if picks == '3':
    system('cls')
    print('barrel = Write code for 2h 52m 42s 62ms, Test code, make branches')
    print('bu wiwi = Making me do this')
    print('Python = coding language')
    sleep(10)
